server {
    listen 80;

    # Folder zawierający pliki naszej aplikacji (wynik ng build)
    root /usr/share/nginx/html;
    index index.html index.htm;

    # GZIP Compression
    gzip on;
    gzip_vary on;
    gzip_min_length 10240;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml application/javascript;
    gzip_disable "MSIE [1-6]\.";

    # Obsługa głównego routingu (Angular SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Przekierowanie ruchu API do backendu 
    # (dzięki temu z frontendu możemy strzelać na `/api/...` zamiast `http://localhost:8000/api/...`)
    location /api/ {
        # Zmienna "api" odnosi się do nazwy kontenera w pliku docker-compose.yml
        proxy_pass http://api:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
